/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konvertersuhu;

/**
 *
 * @author hp
 */
public class KonverterSuhu extends javax.swing.JFrame {

    public Double input;
    public Double Celcius;
    public Double Fahrenheit;
    public Double Reamur;
    public Double Kelvin;
    public String hasilCelcius;
    public String hasilFahrenheit;
    public String hasilReamur;
    public String hasilKelvin;
    
    /**
     * Creates new form KonverterSuhu
     */
    public KonverterSuhu() {
        initComponents();
    }

    private void celcius(){
        input=Double.parseDouble(txtAwal.getText());
        
        Celcius=input;
        Fahrenheit=Celcius*1.8+32;
        Reamur=Celcius*0.8;
        Kelvin=Celcius+273.15;
        
        hasilCelcius=Double.toString(Celcius);
        txtCelcius.setText(hasilCelcius);
        
        hasilFahrenheit=Double.toString(Fahrenheit);
        txtFahrenheit.setText(hasilFahrenheit);
        
        hasilReamur=Double.toString(Reamur);
        txtReamur.setText(hasilReamur);
                
        hasilKelvin=Double.toString(Kelvin);
        txtKelvin.setText(hasilKelvin);
    }
    
    private void fahrenheit(){
        input=Double.parseDouble(txtAwal.getText());
        
        Fahrenheit=input;
        Celcius=(Fahrenheit-32)/1.8;
        Reamur=(Fahrenheit-32)/2.25;
        Kelvin=(Fahrenheit+459.67)/1.8;
        
        hasilCelcius=Double.toString(Celcius);
        txtCelcius.setText(hasilCelcius);
        
        hasilFahrenheit=Double.toString(Fahrenheit);
        txtFahrenheit.setText(hasilFahrenheit);
        
        hasilReamur=Double.toString(Reamur);
        txtReamur.setText(hasilReamur);
        
        hasilKelvin=Double.toString(Kelvin);
        txtKelvin.setText(hasilKelvin);
    }
    
    private void reamur(){
        input=Double.parseDouble(txtAwal.getText());
        
        Reamur=input;
        Celcius=Reamur/0.8;
        Fahrenheit=(Reamur*2.25)+32;
        Kelvin=Reamur/0.8+237.15;
        
        hasilCelcius=Double.toString(Celcius);
        txtCelcius.setText(hasilCelcius);
        
        hasilFahrenheit=Double.toString(Fahrenheit);
        txtFahrenheit.setText(hasilFahrenheit);
        
        hasilReamur=Double.toString(Reamur);
        txtReamur.setText(hasilReamur);
        
        hasilKelvin=Double.toString(Kelvin);
        txtKelvin.setText(hasilKelvin);
    }
    
    private void kelvin(){
        input=Double.parseDouble(txtAwal.getText());
        
        Kelvin=input;
        Celcius=Kelvin-273.15;
        Fahrenheit=Kelvin*1.8-459.67;
        Reamur=(Kelvin-273.15)*0.8;
        
        hasilCelcius=Double.toString(Celcius);
        txtCelcius.setText(hasilCelcius);
        
        hasilFahrenheit=Double.toString(Fahrenheit);
        txtFahrenheit.setText(hasilFahrenheit);
        
        hasilReamur=Double.toString(Reamur);
        txtReamur.setText(hasilReamur);
        
        hasilKelvin=Double.toString(Kelvin);
        txtKelvin.setText(hasilKelvin);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtAwal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtCelcius = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        txtReamur = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txtAwal);
        txtAwal.setBounds(160, 20, 310, 30);

        jLabel1.setText("Suhu Awal        :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 100, 30);

        buttonGroup1.add(rbCelcius);
        rbCelcius.setText("Celcius");
        getContentPane().add(rbCelcius);
        rbCelcius.setBounds(30, 70, 110, 23);

        buttonGroup1.add(rbFahrenheit);
        rbFahrenheit.setText("Fahrenheit");
        getContentPane().add(rbFahrenheit);
        rbFahrenheit.setBounds(30, 110, 140, 23);

        buttonGroup1.add(rbReamur);
        rbReamur.setText("Reamur");
        getContentPane().add(rbReamur);
        rbReamur.setBounds(200, 70, 120, 23);

        buttonGroup1.add(rbKelvin);
        rbKelvin.setText("Kelvin");
        getContentPane().add(rbKelvin);
        rbKelvin.setBounds(200, 110, 110, 23);

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKonversi);
        btnKonversi.setBounds(360, 70, 90, 60);

        btnClear.setText("Reset");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(30, 150, 100, 30);

        btnBatal.setText("Batalkan");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal);
        btnBatal.setBounds(200, 150, 100, 30);

        txtCelcius.setEditable(false);
        getContentPane().add(txtCelcius);
        txtCelcius.setBounds(160, 210, 310, 30);

        txtFahrenheit.setEditable(false);
        getContentPane().add(txtFahrenheit);
        txtFahrenheit.setBounds(160, 250, 310, 30);

        txtReamur.setEditable(false);
        txtReamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReamurActionPerformed(evt);
            }
        });
        getContentPane().add(txtReamur);
        txtReamur.setBounds(160, 290, 310, 30);

        txtKelvin.setEditable(false);
        getContentPane().add(txtKelvin);
        txtKelvin.setBounds(160, 330, 310, 30);

        jLabel2.setText("Celcius");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 214, 110, 20);

        jLabel3.setText("Fahrenheit");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 254, 110, 20);

        jLabel4.setText("Reamur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 294, 110, 20);

        jLabel5.setText("Kelvin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 334, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReamurActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        
        if(rbCelcius.isSelected()){
            celcius();
        }
        else if(rbFahrenheit.isSelected()){
            fahrenheit();
        }
        else if(rbReamur.isSelected()){
            reamur();
        }
        else if(rbKelvin.isSelected()){
            kelvin();
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAwal.setText("");
        txtCelcius.setText("");
        txtFahrenheit.setText("");
        txtReamur.setText("");
        txtKelvin.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonverterSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    private javax.swing.JTextField txtAwal;
    private javax.swing.JTextField txtCelcius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    private javax.swing.JTextField txtReamur;
    // End of variables declaration//GEN-END:variables
}
